### ISSUE TITLE
DOC: Search Results button enhancement

### ISSUE THREAD

**Issue by AditiPrabhakar** [Satyam1923/Spring-Music-Player#125]
### What's wrong with the existing documentation

Instead of putting the search button here, we can put a link saying 'Search Results' that can direct them to other Search Result page that asks for users input, with that we can add better **hover effects** and make button look more visible.

### Add ScreenShots

![Screenshot (85)](https://github.com/Satyam1923/Spring-Music-Player/assets/139689410/c3ec15fc-e33d-4e76-aa98-cd150c65df58)

we can do this similar to:

![Screenshot (86)](https://github.com/Satyam1923/Spring-Music-Player/assets/139689410/1a2b72c0-5871-432b-8996-00e9851f3211)

![Screenshot (87)](https://github.com/Satyam1923/Spring-Music-Player/assets/139689410/005fd9de-2a02-478e-bec4-89cc7183b349)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing [issues](https://github.com/Satyam1923/Spring-Music-Player/issues)
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sooraj002** [comment]
I would like to fix this issue.

**Comment by Azhar-0401** [comment]
*is your feature request related to a problem? Please describe.*
Currently search has not such a good style .

*Describe the solution you'd like*
Adding margin, padding and set allginment and change in style and changes according to search bar

*Additional context*
Assign me this work under GSSoC

Sir i'm Experienced in Frontend Developer , there are some my work link
https://www.shinnextream.in/
https://innovationnitrr.netlify.app/

so, please assign me

**Comment by Satyam1923** [comment]
@AditiPrabhakar you wanna help with designing?

**Comment by KomalSrivastava** [comment]
@Satyam1923 Picture this: a seamless user experience that not only enhances visibility but also streamlines navigation. Instead of a conventional search button, why not entice users with a sleek and inviting "Search Results" link? This link will seamlessly guide them to a dedicated Search Results page, where they can input their query with ease.

But wait, there's more! Alongside this intuitive link, let's sprinkle in some captivating hover effects to elevate the visual appeal and draw users in. With every hover, they'll be greeted with a delightful animation that sparks curiosity and encourages exploration.

I'm enthusiastic about taking on this task and transforming our search functionality into something truly spectacular. Please entrust me with this assignment under GSSoC'24, where I'll infuse creativity and innovation into every aspect. Together, let's create an experience that not only meets but exceeds user expectations!

**Comment by Satyam1923** [comment]
Done.
